/**
 * Writes config.js for the static site. Reads, in order:
 * 1) process.env (set in Netlify, Vercel, Cloudflare, GitHub Actions, etc.)
 * 2) .env / .env.local (local dev) — only fills in keys that are not already set
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * @param {string} content
 * @returns {void}
 */
function applyEnvFile(content) {
  for (const line of content.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq < 0) continue;
    const key = t.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let val = t.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    // Host / CI always wins; file only fills missing keys
    if (process.env[key] == null || process.env[key] === "") {
      process.env[key] = val;
    }
  }
}

for (const f of [join(root, ".env"), join(root, ".env.local")]) {
  try {
    if (existsSync(f)) applyEnvFile(readFileSync(f, "utf8"));
  } catch (e) {
    console.warn("[labnlobs] Could not read " + f + ":", e.message);
  }
}

// Aliases if your host uses different names (e.g. Supabase dashboard / templates)
if (!process.env.SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_URL) {
  process.env.SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
}
if (!process.env.SUPABASE_ANON_KEY && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  process.env.SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
}
if (!process.env.SUPABASE_ANON_KEY && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) {
  process.env.SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
}
if (!process.env.SUPABASE_ANON_KEY && process.env.SB_PUBLISHABLE_KEY) {
  process.env.SUPABASE_ANON_KEY = process.env.SB_PUBLISHABLE_KEY;
}

const supabaseUrl = (process.env.SUPABASE_URL || "").trim();
const supabaseKey = (process.env.SUPABASE_ANON_KEY || "").trim();
const tableName = (process.env.SUPABASE_TABLE || "email").trim();

if (!supabaseUrl || !supabaseKey) {
  console.warn(
    "[labnlobs] SUPABASE_URL and SUPABASE_ANON_KEY are required for the waitlist. " +
      "Set them in your deploy provider (Build environment variables) or in .env for local. " +
      "Writing config.js with empty values so the build can still finish."
  );
} else {
  console.log(
    "[labnlobs] Wrote config.js (table: " + tableName + ")"
  );
}

const payload = {
  SUPABASE_URL: supabaseUrl,
  SUPABASE_ANON_KEY: supabaseKey,
  SUPABASE_TABLE: tableName,
};

const out =
  "/* Auto-generated by scripts/inject-env.mjs — do not commit */\n" +
  `window.__APP_ENV__ = ${JSON.stringify(payload, null, 0)};\n`;

// Vercel (and other hosts) use ./public as the static output; config.js must live next to index.html
const outDir = join(root, "public");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "config.js"), out, "utf8");
process.exit(0);
